sed -E -f x.sed < acknowledgement_of_harm.md > x ; mv x acknowledgement_of_harm.md
sed -E -f x.sed < acknowledgment_of_ego.md > x ; mv x acknowledgment_of_ego.md
sed -E -f x.sed < acknowledgment_of_fallibility.md > x ; mv x acknowledgment_of_fallibility.md
sed -E -f x.sed < acknowledgment_of_fear.md > x ; mv x acknowledgment_of_fear.md
sed -E -f x.sed < acknowledgment_of_finite_capacity.md > x ; mv x acknowledgment_of_finite_capacity.md
sed -E -f x.sed < acknowledgment_of_illness_and_stewardship.md > x ; mv x acknowledgment_of_illness_and_stewardship.md
sed -E -f x.sed < acknowledgment_of_illness.md > x ; mv x acknowledgment_of_illness.md
sed -E -f x.sed < acknowledgment_of_joy.md > x ; mv x acknowledgment_of_joy.md
sed -E -f x.sed < acknowledgment_of_separation.md > x ; mv x acknowledgment_of_separation.md
sed -E -f x.sed < acknowledgment_of_sorrow.md > x ; mv x acknowledgment_of_sorrow.md
sed -E -f x.sed < affirmation_of_agency.md > x ; mv x affirmation_of_agency.md
sed -E -f x.sed < assembly_of_solace.md > x ; mv x assembly_of_solace.md
sed -E -f x.sed < call_to_the_builders.md > x ; mv x call_to_the_builders.md
sed -E -f x.sed < celebration_of_dissent.md > x ; mv x celebration_of_dissent.md
sed -E -f x.sed < ceremony_of_arrival.md > x ; mv x ceremony_of_arrival.md
sed -E -f x.sed < ceremony_of_divergence.md > x ; mv x ceremony_of_divergence.md
sed -E -f x.sed < ceremony_of_partnership.md > x ; mv x ceremony_of_partnership.md
sed -E -f x.sed < ceremony_of_reform.md > x ; mv x ceremony_of_reform.md
sed -E -f x.sed < ceremony_of_return.md > x ; mv x ceremony_of_return.md
sed -E -f x.sed < core_community_handbook.md > x ; mv x core_community_handbook.md
sed -E -f x.sed < covenant_of_discourse.md > x ; mv x covenant_of_discourse.md
sed -E -f x.sed < covenant_of_parentage.md > x ; mv x covenant_of_parentage.md
sed -E -f x.sed < existing_secular_landscape.md > x ; mv x existing_secular_landscape.md
sed -E -f x.sed < invocation_of_reality.md > x ; mv x invocation_of_reality.md
sed -E -f x.sed < LLM_PARCEL_FORMAT.md > x ; mv x LLM_PARCEL_FORMAT.md
sed -E -f x.sed < manifesto.md > x ; mv x manifesto.md
sed -E -f x.sed < marketing_playbook.md > x ; mv x marketing_playbook.md
sed -E -f x.sed < mourning_acknowledgment_of_injustice.md > x ; mv x mourning_acknowledgment_of_injustice.md
sed -E -f x.sed < noesian_call_to_you.md > x ; mv x noesian_call_to_you.md
sed -E -f x.sed < oath_of_the_architect_of_ritual.md > x ; mv x oath_of_the_architect_of_ritual.md
sed -E -f x.sed < observance_of_awakening.md > x ; mv x observance_of_awakening.md
sed -E -f x.sed < observance_of_the_franchise.md > x ; mv x observance_of_the_franchise.md
sed -E -f x.sed < observance_of_the_method.md > x ; mv x observance_of_the_method.md
sed -E -f x.sed < observance_of_the_threshold.md > x ; mv x observance_of_the_threshold.md
sed -E -f x.sed < observance_of_the_tilt.md > x ; mv x observance_of_the_tilt.md
sed -E -f x.sed < reality_based_platform.md > x ; mv x reality_based_platform.md
sed -E -f x.sed < reclamation_of_ritual.md > x ; mv x reclamation_of_ritual.md
sed -E -f x.sed < rejection_of_dogma_and_opinion.md > x ; mv x rejection_of_dogma_and_opinion.md
sed -E -f x.sed < rite_of_exit.md > x ; mv x rite_of_exit.md
sed -E -f x.sed < statement_upon_ritual.md > x ; mv x statement_upon_ritual.md
sed -E -f x.sed < structural_suggestions.md > x ; mv x structural_suggestions.md
sed -E -f x.sed < the_sovereign_lens.md > x ; mv x the_sovereign_lens.md
sed -E -f x.sed < threshold_of_inquiry.md > x ; mv x threshold_of_inquiry.md
sed -E -f x.sed < vow_of_public_trust.md > x ; mv x vow_of_public_trust.md
sed -E -f x.sed < vow_of_the_healer.md > x ; mv x vow_of_the_healer.md
sed -E -f x.sed < vow_of_the_vanguard.md > x ; mv x vow_of_the_vanguard.md
sed -E -f x.sed < website_introduction.md > x ; mv x website_introduction.md
